"""v1.3.0_beta.1

Revision ID: ed6e0915a238
Revises: 5a168c28eace
Create Date: 2026-09-15 00:17:22.658871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed6e0915a238'
down_revision: Union[str, Sequence[str], None] = '5a168c28eace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum').create(op.get_bind())
    op.add_column('materials', sa.Column('generation_type', sa.Enum('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum'), server_default='USER_CREATED', nullable=False))
    op.add_column('materials', sa.Column('source_reference', sa.String(length=500), nullable=True))
    op.add_column('materials', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_materials_generation_type'), 'materials', ['generation_type'], unique=False)
    op.create_index(op.f('ix_materials_source_id'), 'materials', ['source_id'], unique=False)
    op.create_foreign_key(None, 'materials', 'materials', ['source_id'], ['id'], ondelete='SET NULL')
    op.add_column('study_spaces', sa.Column('learning_output_language', sa.String(length=10), server_default='en', nullable=False))
    op.drop_column('study_spaces', 'learning_language')
    op.add_column('tasks', sa.Column('generation_type', sa.Enum('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum'), server_default='USER_CREATED', nullable=False))
    op.drop_index(op.f('ix_tasks_source_type'), table_name='tasks')
    op.create_index(op.f('ix_tasks_generation_type'), 'tasks', ['generation_type'], unique=False)
    op.drop_column('tasks', 'source_type')
    op.add_column('topics', sa.Column('generation_type', sa.Enum('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum'), server_default='USER_CREATED', nullable=False))
    op.add_column('topics', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_topics_source_material_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_source_type'), table_name='topics')
    op.create_index(op.f('ix_topics_generation_type'), 'topics', ['generation_type'], unique=False)
    op.create_index(op.f('ix_topics_source_id'), 'topics', ['source_id'], unique=False)
    op.drop_constraint(op.f('fk_topics_source_material_id_materials'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'materials', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_column('topics', 'source_material_id')
    op.drop_column('topics', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum').create(op.get_bind())
    op.add_column('topics', sa.Column('source_type', postgresql.ENUM('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='source_type_enum'), server_default=sa.text("'USER_CREATED'::source_type_enum"), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('source_material_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_topics_source_material_id_materials'), 'topics', 'materials', ['source_material_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_topics_source_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_generation_type'), table_name='topics')
    op.create_index(op.f('ix_topics_source_type'), 'topics', ['source_type'], unique=False)
    op.create_index(op.f('ix_topics_source_material_id'), 'topics', ['source_material_id'], unique=False)
    op.drop_column('topics', 'source_id')
    op.drop_column('topics', 'generation_type')
    op.add_column('tasks', sa.Column('source_type', postgresql.ENUM('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='source_type_enum'), server_default=sa.text("'USER_CREATED'::source_type_enum"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tasks_generation_type'), table_name='tasks')
    op.create_index(op.f('ix_tasks_source_type'), 'tasks', ['source_type'], unique=False)
    op.drop_column('tasks', 'generation_type')
    op.add_column('study_spaces', sa.Column('learning_language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('study_spaces', 'learning_output_language')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_index(op.f('ix_materials_source_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_generation_type'), table_name='materials')
    op.drop_column('materials', 'source_id')
    op.drop_column('materials', 'source_reference')
    op.drop_column('materials', 'generation_type')
    postgresql.ENUM('USER_CREATED', 'SOURCE_EXTRACTED', 'AI_INFERRED', 'MIXED', name='generation_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
