from typing import Dict, Any, Optional, Protocol

class AIProvider(Protocol):
    def is_available(self) -> bool: ...
    def generate_study_topics(self, input_text: str, is_topic_name: bool = False, title: Optional[str] = None) -> Dict[str, Any]: ...
    def extract_curriculum(self, text: str, title: Optional[str] = None) -> Dict[str, Any]: ...
    def chat_assistant(self, message: str, mode: str = "explain", context_topic: Optional[str] = None, current_study_space: Optional[str] = None) -> Dict[str, Any]: ...
    def generate_verification_quiz(self, subtopic_name: str) -> Dict[str, Any]: ...
    def generate_completion(self, prompt: str) -> str: ...
    def analyze_weakness(self, topic_title: str, metrics: Dict[str, Any]) -> Dict[str, Any]: ...
    def suggest_debug_hypothesis(self, problem: str, symptom: str, logs: str = "") -> Dict[str, str]: ...
